# Generated by Django 4.0.10 on 2023-09-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='user_registration.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.user')),
            ],
            options={
                'unique_together': {('user', 'following')},
            },
        ),
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='user_registration.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.user')),
            ],
            options={
                'unique_together': {('user', 'follower')},
            },
        ),
    ]
